[functions]
"*" = { }

[[plugins]]
package = "."
origin = "config"
inputs = { }

[build]
environment = { }
publish = "/workspaces/netlify-plugin-identity-sso"
publishOrigin = "default"
services = { }
command = "echo onBuild"
commandOrigin = "config"

  [build.processing]
  css = { }
  html = { }
  images = { }
  js = { }

[[redirects]]
from = "/*"
to = "/:splat"
status = 404

  [redirects.conditions]
  Role = [ "netlify" ]

[[redirects]]
from = "/"
to = "/_netlify-sso"
status = 401
force = true

[[redirects]]
from = "/*"
to = "/"
status = 302
force = true
